version: '3'

services:
  frontend:
    image: frontend:latest
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  backend:
    image: backend:latest
    restart: on-failure:5
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DB_HOST=jdbc:mysql://mysqldb:3306/employeedb?useSSL=false
      - MYSQL_DB_USER=sa
      - MYSQL_DB_PASS=123456
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=123456
