apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/jniltinho/desafio-devops/backend:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_DB_HOST
            value: jdbc:mysql://mysqldb:3306/backenddb?useSSL=false
          - name: MYSQL_DB_USER
            value: sa
          - name: MYSQL_DB_PASS
            value: 123456
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
