## Create K8S Cluster DigitalOcean
name: "CREATE K8S CLUSTER DO"

on:
  push:
    branches:
      - infra
  workflow_dispatch:

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
  INGRESS_DEPLOY: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/do/deploy.yaml'
  CLUSTER_NAME: 'prod01'


jobs:
  k8s-cluster-do:
    runs-on: ubuntu-latest
    container:
      image: jniltinho/deploy-debian-k8s:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Format and Init
      run: cd infra/k8s-cluster-do/; terraform fmt -check && terraform init
    
    - name: Terraform Validade and Apply
      run: cd infra/k8s-cluster-do/; terraform validate && terraform apply --auto-approve
      
    - name: Add K8s Config for kubectl
      run: doctl kubernetes cluster list; doctl kubernetes cluster kubeconfig save ${CLUSTER_NAME}      
      
    - name: Install NGINX Ingress Controller
      run: kubectl apply -f ${INGRESS_DEPLOY}; kubectl get pods -n=ingress-nginx; kubectl get svc -n=ingress-nginx     

    - name: K8s Create Default Namespace
      run: kubectl create ns prod; kubectl create ns homol; kubectl create ns dev; kubectl get ns
