## Create K8S Cluster DigitalOcean
name: "CREATE K8S CLUSTER DO"

on:
  push:
    branches:
      - infra
  workflow_dispatch:


env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
  INGRESS_DEPLOY: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/do/deploy.yaml'
  TZ: 'America/Sao_Paulo'


jobs:
  k8s-cluster-do:
    runs-on: ubuntu-latest
    container:
      image: jniltinho/deploy-debian-k8s:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: cd infra/k8s-cluster-do/; terraform fmt -check
    - name: Terraform Init
      run: cd infra/k8s-cluster-do/; terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Validate
      run: cd infra/k8s-cluster-do/; terraform validate

    # Create k8s Cluster DigitalOcean
    - name: Create Cluster DO
      run: cd infra/k8s-cluster-do/; terraform apply --auto-approve
      
    - name: Add K8s Config for kubectl
      run: doctl kubernetes cluster list; doctl kubernetes cluster kubeconfig save cluster01      
      
    - name: Install NGINX Ingress Controller
      run: kubectl apply -f ${INGRESS_DEPLOY}; kubectl get pods -n=ingress-nginx; kubectl get svc -n=ingress-nginx     

    - name: K8s Create Default Namespace
      run: kubectl create ns prod; kubectl create ns homol; kubectl create ns dev
